### ISSUE TITLE
openai.APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by XiaokunSun** [runjiali-rl/threestudio-dreambeast#1]
Excellent work! Maybe because I am in China, I cannot connect to the openai api and get the following error. Does anyone have a simple alternative?
```
Import times for custom modules:
   0.0 seconds: custom/threestudio-mvdream
   0.0 seconds: custom/threestudio-gaussiandreamer
   0.3 seconds: custom/threestudio-dreambeast
   0.5 seconds: custom/threestudio-lrm
   1.7 seconds: custom/threestudio-progressive3d

Seed set to 0
[INFO] Loading Multiview Diffusion ...
Loading model from config: sd-v2-base.yaml
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Loading model from cache file: /root/.cache/huggingface/hub/models--MVDream--MVDream/snapshots/d14ac9d78c48c266005729f2d5633f6c265da467/sd-v2.1-base-4view.pt
[INFO] Loaded Multiview Diffusion!
Replaced forward method in model: LatentDiffusionInterface
Replaced forward method in model: DiffusionWrapper
Replaced forward method in model: SD3Transformer2DModel
Replaced forward method in model: SD3Transformer2DModel
Replaced forward method in model: SD3Transformer2DModel
Replaced forward method in layer: model.diffusion_model.input_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.1
Replaced forward method in layer: model.diffusion_model.input_blocks.1.1
Replaced forward method in layer: model.diffusion_model.input_blocks.1.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.1.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.input_blocks.2
Replaced forward method in layer: model.diffusion_model.input_blocks.2.1
Replaced forward method in layer: model.diffusion_model.input_blocks.2.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.2.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.input_blocks.3
Replaced forward method in layer: model.diffusion_model.input_blocks.4
Replaced forward method in layer: model.diffusion_model.input_blocks.4.1
Replaced forward method in layer: model.diffusion_model.input_blocks.4.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.4.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.input_blocks.5
Replaced forward method in layer: model.diffusion_model.input_blocks.5.1
Replaced forward method in layer: model.diffusion_model.input_blocks.5.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.5.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.input_blocks.6
Replaced forward method in layer: model.diffusion_model.input_blocks.7
Replaced forward method in layer: model.diffusion_model.input_blocks.7.1
Replaced forward method in layer: model.diffusion_model.input_blocks.7.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.7.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.input_blocks.8
Replaced forward method in layer: model.diffusion_model.input_blocks.8.1
Replaced forward method in layer: model.diffusion_model.input_blocks.8.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.8.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.input_blocks.9
Replaced forward method in layer: model.diffusion_model.input_blocks.10
Replaced forward method in layer: model.diffusion_model.input_blocks.11
Replaced forward method in model: SD3Transformer2DModel
Replaced forward method in layer: model.diffusion_model.middle_block
Replaced forward method in layer: model.diffusion_model.middle_block.1
Replaced forward method in layer: model.diffusion_model.middle_block.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.middle_block.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.middle_block.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.middle_block.1.transformer_blocks.0.attn2
Replaced forward method in model: SD3Transformer2DModel
Replaced forward method in layer: model.diffusion_model.output_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.1
Replaced forward method in layer: model.diffusion_model.output_blocks.2
Replaced forward method in layer: model.diffusion_model.output_blocks.3
Replaced forward method in layer: model.diffusion_model.output_blocks.3.1
Replaced forward method in layer: model.diffusion_model.output_blocks.3.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.3.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.4
Replaced forward method in layer: model.diffusion_model.output_blocks.4.1
Replaced forward method in layer: model.diffusion_model.output_blocks.4.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.4.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.5
Replaced forward method in layer: model.diffusion_model.output_blocks.5.1
Replaced forward method in layer: model.diffusion_model.output_blocks.5.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.5.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.6
Replaced forward method in layer: model.diffusion_model.output_blocks.6.1
Replaced forward method in layer: model.diffusion_model.output_blocks.6.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.6.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.7
Replaced forward method in layer: model.diffusion_model.output_blocks.7.1
Replaced forward method in layer: model.diffusion_model.output_blocks.7.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.7.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.8
Replaced forward method in layer: model.diffusion_model.output_blocks.8.1
Replaced forward method in layer: model.diffusion_model.output_blocks.8.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.8.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.9
Replaced forward method in layer: model.diffusion_model.output_blocks.9.1
Replaced forward method in layer: model.diffusion_model.output_blocks.9.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.9.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.10
Replaced forward method in layer: model.diffusion_model.output_blocks.10.1
Replaced forward method in layer: model.diffusion_model.output_blocks.10.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.10.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2
Replaced forward method in layer: model.diffusion_model.output_blocks.11
Replaced forward method in layer: model.diffusion_model.output_blocks.11.1
Replaced forward method in layer: model.diffusion_model.output_blocks.11.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.11.1.transformer_blocks.0
Replaced forward method in layer: model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1
Replaced forward method in layer: model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2
Replaced forward method in model: SD3Transformer2DModel
Loading checkpoint shards: 100%|████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.71it/s]
Loading pipeline components...:  33%|██████████████▎                            | 3/9 [00:01<00:03,  1.81it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|███████████████████████████████████████████| 9/9 [00:02<00:00,  3.48it/s]
Replaced forward method in model: SD3Transformer2DModel
Replaced forward method in layer: transformer_blocks.0
Replaced processor in layer: transformer_blocks.0
Replaced forward method in layer: transformer_blocks.1
Replaced processor in layer: transformer_blocks.1
Replaced forward method in layer: transformer_blocks.2
Replaced processor in layer: transformer_blocks.2
Replaced forward method in layer: transformer_blocks.3
Replaced processor in layer: transformer_blocks.3
Replaced forward method in layer: transformer_blocks.4
Replaced processor in layer: transformer_blocks.4
Replaced forward method in layer: transformer_blocks.5
Replaced processor in layer: transformer_blocks.5
Replaced forward method in layer: transformer_blocks.6
Replaced processor in layer: transformer_blocks.6
Replaced forward method in layer: transformer_blocks.7
Replaced processor in layer: transformer_blocks.7
Replaced forward method in layer: transformer_blocks.8
Replaced processor in layer: transformer_blocks.8
Replaced forward method in layer: transformer_blocks.9
Replaced processor in layer: transformer_blocks.9
Replaced forward method in layer: transformer_blocks.10
Replaced processor in layer: transformer_blocks.10
Replaced forward method in layer: transformer_blocks.11
Replaced processor in layer: transformer_blocks.11
Replaced forward method in layer: transformer_blocks.12
Replaced processor in layer: transformer_blocks.12
Replaced forward method in layer: transformer_blocks.13
Replaced processor in layer: transformer_blocks.13
Replaced forward method in layer: transformer_blocks.14
Replaced processor in layer: transformer_blocks.14
Replaced forward method in layer: transformer_blocks.15
Replaced processor in layer: transformer_blocks.15
Replaced forward method in layer: transformer_blocks.16
Replaced processor in layer: transformer_blocks.16
Replaced forward method in layer: transformer_blocks.17
Replaced processor in layer: transformer_blocks.17
Replaced forward method in layer: transformer_blocks.18
Replaced processor in layer: transformer_blocks.18
Replaced forward method in layer: transformer_blocks.19
Replaced processor in layer: transformer_blocks.19
Replaced forward method in layer: transformer_blocks.20
Replaced processor in layer: transformer_blocks.20
Replaced forward method in layer: transformer_blocks.21
Replaced processor in layer: transformer_blocks.21
Replaced forward method in layer: transformer_blocks.22
Replaced processor in layer: transformer_blocks.22
Replaced forward method in layer: transformer_blocks.23
Replaced processor in layer: transformer_blocks.23
Traceback (most recent call last):
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "launch.py", line 301, in <module>
    main(args, extras)
  File "launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/data1/SunXiaoKun/Project/threestudio/threestudio/systems/base.py", line 51, in __init__
    self.configure()
  File "/data1/SunXiaoKun/Project/threestudio/custom/threestudio-dreambeast/system/dreambeast.py", line 79, in configure
    self.part_prompts = animal_part_extractor(self.cfg.prompt_processor.prompt,
  File "/data1/SunXiaoKun/Project/threestudio/custom/threestudio-dreambeast/system/attention_ops/attention_stable_diffusion.py", line 971, in animal_part_extractor
    chat_completion = client.chat.completions.create(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/resources/chat/completions.py", line 704, in create
    return self._post(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_diffuers/lib/python3.8/site-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

**Comment by runjiali-rl** [comment]
Hi Xiaokun!

Thank you for trying the code. I will provide an interface that accepts user-defined part descriptions and a few extracted part-affinity maps in the next few days. I will get back to you once it's done. 

Best,
Runjia

**Comment by XiaokunSun** [comment]
> Hi Xiaokun!
> 
> Thank you for trying the code. I will provide an interface that accepts user-defined part descriptions and a few extracted part-affinity maps in the next few days. I will get back to you once it's done.
> 
> Best, Runjia

Thank you for your reply! That's great! After all, it's not a convenient thing for some researchers to call the OpenAI API. Finally, thank you for your excellent work. I like this interesting idea very much!
